import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Menu from '@/components/Menu'
import Footer from '@/components/Footer'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
  title: 'Lory Art Crochê',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <Providers>
          <div className="w-full max-w-2xl md:max-w-7xl ml-auto mr-auto px-6">
            <Menu />
            <div className="mt-10 flex-auto">{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
